apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: devops-part3
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: movie-review-backend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5001
          env:
            - name: NODE_ENV
              value: production
            - name: PORT
              value: "5001"
            - name: MONGO_URI
              value: mongodb://mongo:27017/movie-review-platform
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: movie-secrets
                  key: jwt-secret
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: devops-part3
spec:
  selector:
    app: backend
  ports:
    - port: 5001
      targetPort: 5001
  type: ClusterIP